version: "3.9"
services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
